apiVersion: v1
kind: Secret
metadata:
  name: users-api-secrets
  namespace: backend-api
type: Opaque
data:
  connection-string: U2VydmVyPW15c3FsLXN2Yy5kYXRhYmFzZXMuc3ZjLmNsdXN0ZXIubG9jYWw7RGF0YWJhc2U9RGlzdHJpYnV0ZWRTeXN0ZW1zO1VzZXIgSWQ9cm9vdDtQYXNzd29yZD1qZmFhcDIzNDtTc2xNb2RlPVByZWZlcnJlZDs=

