apiVersion: v1
kind: Service
metadata:
  name: users-api-svc
  namespace: backend-api
spec:
  selector:
    app: users-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP