apiVersion: v1
kind: Service
metadata:
  name: groups-api-svc
  namespace: backend-api
spec:
  selector:
    app: groups-api
  ports:
    - port: 9091
      targetPort: 9091
  type: LoadBalancer